name: smb_docker_project

services:
  smb_container:
    image: ghcr.io/ethz-robotx/smb_docker:latest
    container_name: smb_container
    privileged: true
    pull_policy: always
    restart: "no"
    network_mode: host
    user: robotx
    command: "bash /post_create_config"
    working_dir: ${WORKSPACE_DIR:?error}
    configs:
      - post_create_config
    env_file: .env
    environment:
      - QT_X11_NO_MITSHM=1
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./scripts:/scripts:rw
      - smb_volume:${WORKSPACE_DIR:?error}:rw

volumes:
  smb_volume:
    name: smb_volume

configs:
  post_create_config:
    file: ./scripts/post-create.sh