name: smb_docker_vnc

services:
  smb_container:
    image: ghcr.io/ethz-robotx/smb_docker:latest
    container_name: smb_container
    privileged: true
    pull_policy: always
    restart: "no"
    network_mode: host
    user: robotx
    command: ["bash", "/post_create_config"]
    working_dir: /workspaces/rss_workspace
    configs:
      - post_create_config
    env_file: .env
    environment:
      - QT_X11_NO_MITSHM=1
      - DISPLAY=:1
      - WORKSPACE_DIR=/workspaces/rss_workspace
      - MPLBACKEND=Qt5Agg
    volumes:
      - smb_volume:/workspaces/rss_workspace:rw

volumes:
  smb_volume:
    name: smb_volume

configs:
  post_create_config:
    file: ./scripts/post-create.sh