name: build-smb-base-image

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'feature/**'
      - 'fix/**'
    paths:
      - '.github/.devcontainer/**'
      - '.github/workflows/build_push.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      DOCKERFILE_PATH: ./.github/.devcontainer/Dockerfile
      BUILD_CONTEXT: ./.github/.devcontainer
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: latest=false
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}},priority=700

      - name: Build and push Docker image
        id: docker-build
        uses: docker/build-push-action@v5
        env:
          BUILDX_NO_DEFAULT_ATTESTATIONS: 1
        with:
          context: ${{ env.BUILD_CONTEXT }}
          file: ${{ env.DOCKERFILE_PATH }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          no-cache-filters: cacher
          provenance: false
      - name: Update devcontainer.json
        uses: restackio/update-json-values-action@f3c458e872e467a6810b446755acf5771354aef1
        with:
          file: ./.devcontainer/devcontainer.json
          values: >-
            {
              "build.args.BASE_IMAGE": "${{ steps.docker-build.outputs.metadata['image.name'] }}",
              "initializeCommand": "docker pull ${{ steps.docker-build.outputs.metadata['image.name'] }}"
            }
      - name: Commit and push changes
        if: ${{ format('refs/heads/{0}', github.event.repository.default_branch) != github.ref }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update devcontainer.json base image to ${{ steps.docker-build.outputs.metadata['image.name'] }}