name: build-devcontainer

run-name: build@${{ github.ref_name }}

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      DOCKERFILE_PATH: ./.github/.devcontainer/Dockerfile
      BUILD_CONTEXT: ./.github/.devcontainer
    permissions:
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
                  
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/ethz-robotx/smb_docker
          cacheFrom: ghcr.io/ethz-robotx/smb_docker
          platform: linux/amd64,linux/arm64
          subFolder: .github
          push: always